// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Fileiphone8Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void fileiphone8() {
    driver.get("https://www.lazada.vn/#?");
    driver.manage().window().setSize(new Dimension(786, 808));
    driver.findElement(By.id("q")).click();
    driver.findElement(By.id("q")).sendKeys("i phone x");
    driver.findElement(By.linkText("SEARCH")).click();
    driver.findElement(By.cssSelector(".Bm3ON:nth-child(2) .RfADt")).click();
    assertThat(driver.findElement(By.linkText("[E-Voucher] Sở hữu lPhone 15 Pro Max 512Gb - Basic 2024")).getText(), is("[E-Voucher] Sở hữu lPhone 15 Pro Max 512Gb - Basic 2024"));
    js.executeScript("window.scrollTo(0,772.7999877929688)");
    js.executeScript("window.scrollTo(0,992.7999877929688)");
    js.executeScript("window.scrollTo(0,1238.4000244140625)");
    js.executeScript("window.scrollTo(0,1543.199951171875)");
    js.executeScript("window.scrollTo(0,1546.4000244140625)");
    js.executeScript("window.scrollTo(0,1690.4000244140625)");
    js.executeScript("window.scrollTo(0,1911.199951171875)");
    js.executeScript("window.scrollTo(0,922.4000244140625)");
    js.executeScript("window.scrollTo(0,540.7999877929688)");
    driver.findElement(By.cssSelector(".Bm3ON:nth-child(6) .buTCk")).click();
    driver.findElement(By.linkText("SEARCH")).click();
  }
}
